spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/website
    username: postgres
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  liquibase:
    enabled: true
    change-log: classpath:/db.changelog/db.changelog-master.yaml
app:
  db-init: true
server:
  port: 9994