version: '3.1'
services:
  postgres:
    image: postgres:11.4
    environment:
      POSTGRES_DB: website
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
